CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI";

CREATE TABLE USERS (
    ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50)
);

-- PROCEDIMEINTOS ALMACENADOS
--INSERTAR
CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER 
BEGIN 
    INSERT INTO USERS(NAME) VALUES (_NAME); 
END;

CALL spInsertUser('manolo');

--MOSTRAR TODO
CREATE PROCEDURE `spFindAllUser`() NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USERS; 
END;

CALL spFindAllUser();

--MOSTRAR UNO
CREATE PROCEDURE `spFindUser`(IN `_ID` INT(5)) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USERS WHERE ID = _ID; 
END;

CALL spFindUser();

--ACTUALIZAR
CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT(5), IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER 
BEGIN 
    UPDATE USERS SET NAME = _NAME WHERE ID = _ID; 
END;

CALL `spUpdateUser`(1, 'ramon');

--ELIMINAR
CREATE PROCEDURE `spDeleteUser`(IN `_ID` INT(5)) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER 
BEGIN 
    DELETE FROM USERS WHERE ID = _ID; 
END;

CALL spDeleteUser(1);